### ISSUE TITLE
TypeError when initializing model

### ISSUE THREAD

**Issue by ElpadoCan** [julianpietsch/baby#1]
Hi Julian, 

when I ran the minmal code you can see below I get a TypeError. I pasted the traceback below. Would you know what the issue is? Thanks! 

```python
from baby import modelsets
from baby import BabyCrawler

from baby import modelsets
meta = modelsets.meta()

BABY_MODELS = list(meta.keys())

model_type = ''
brain = modelsets.get(BABY_MODELS[0])
```
I get this error
```shell
Traceback (most recent call last):
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\ops\operation.py", line 234, in from_config
    return cls(**config)
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\layers\convolutional\conv2d_transpose.py", line 115, in __init__
    super().__init__(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\layers\convolutional\base_conv_transpose.py", line 94, in __init__
    super().__init__(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\layers\layer.py", line 266, in __init__
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to Conv2DTranspose: {'groups': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\OneDrive\01_Postdoc_HMGU\GitHub\Cell_ACDC\cellacdc\test.py", line 10, in <module>
    brain = modelsets.get(BABY_MODELS[0])
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\baby\modelsets.py", line 405, in get
    return BabyBrain(modelset_path=modelset_id, **get_params(modelset_id),
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\baby\brain.py", line 200, in __init__
    self.morph_model = models.load_model(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\saving\saving_api.py", line 189, in load_model
    return legacy_h5_format.load_model_from_hdf5(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 133, in load_model_from_hdf5
    model = saving_utils.model_from_config(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 85, in model_from_config
    return serialization.deserialize_keras_object(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\legacy\saving\serialization.py", line 495, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\models\model.py", line 521, in from_config
    return functional_from_config(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\models\functional.py", line 477, in functional_from_config
    process_layer(layer_data)
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\models\functional.py", line 457, in process_layer
    layer = saving_utils.model_from_config(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 85, in model_from_config
    return serialization.deserialize_keras_object(
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\legacy\saving\serialization.py", line 504, in deserialize_keras_object
    deserialized_obj = cls.from_config(cls_config)
  File "C:\Users\elpad\miniforge3\envs\acdc\lib\site-packages\keras\src\ops\operation.py", line 236, in from_config
    raise TypeError(
TypeError: Error when deserializing class 'Conv2DTranspose' using config={'name': 'up_3', 'trainable': True, 'dtype': 'float32', 'filters': 32, 'kernel_size': [2, 2], 'strides':
[2, 2], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'output_padding': None}.

Exception encountered: Unrecognized keyword arguments passed to Conv2DTranspose: {'groups': 1}
```

**Comment by julianpietsch** [comment]
Hi Francesco!

Thanks for raising this issue. I believe the error occurs during model loading- it seems the latest version(s) of Tensorflow no longer load our models. I’ll restrict the install requirements to limit the version of Tensorflow in fresh environments. 

In the meantime, the easiest way to fix the problem is to downgrade your Tensorflow version. Something like `pip install -U tensorflow==2.14` should work.

**Comment by ElpadoCan** [comment]
I confirm that solves the issue thanks!
